### ISSUE TITLE
#footer-container Issues

### ISSUE THREAD

**Issue by moseke** [olefredrik/FoundationPress#1060]
For some reason, #footer-container causes so many problems! 

If I delete the whole block of code, I get console errors:
![screen shot 2017-08-28 at 1 41 01 pm](https://user-images.githubusercontent.com/5262718/29792869-b5b0da44-8bf6-11e7-8a99-6a7f6af34139.png)

If I leave it in there it creates large blocks of empty space.
![screen-shot-2017-08-28-at-1 29 51-pm](https://user-images.githubusercontent.com/5262718/29792969-05fc77e2-8bf7-11e7-942d-0cc3040d6ff5.jpg)

I don't need this container or it's contents for anything. What are your suggestions?

**Comment by colin-marshall** [comment]
@moseke 
**Please List the Following:**
* OS & version:
* Node version (node -v) [Node v4+ is required] :
* FoundationPress version (see line 3 in package.json):
* Foundation version (see dependencies in package.json) :

Also please show us what your `footer.php` file looks like prior to removing `#footer-container`.

**Comment by moseke** [comment]
OS: Mac 10.12.6
Node: 7.9.0
FoundationPress V: 2.9.0
Foundation: 6

![screen shot 2017-08-29 at 1 56 50 pm](https://user-images.githubusercontent.com/5262718/29843798-f1ff39b6-8cc1-11e7-81e4-d51bbc26447f.png)
![screen shot 2017-08-29 at 1 56 52 pm](https://user-images.githubusercontent.com/5262718/29843800-f74d6244-8cc1-11e7-9b13-faaea86ebbef.png)

**Comment by colin-marshall** [comment]
@moseke thanks for that! For future reference, please copy/paste code into your message and format it using [Markdown](https://guides.github.com/features/mastering-markdown/) instead of posting screenshots.

To resolve your issue, simply delete the file `assets/javascript/custom/stickyfooter.js` which selects the `#footer-container` element. When you removed the element, that script was trying to select an element that no longer exists, which is why you were getting the console errors.
