### ISSUE TITLE
WooCommerce 3.0 - Hidden products showing in search results

### ISSUE THREAD

**Issue by newtlabs** [olefredrik/FoundationPress#1068]
**How can this bug be reproduced?**

1. Step one - add a product as hidden
2. Step two - search for product
3. Step three - see hidden product shown in search results

**What did you expect to happen?**

I expected to see no hidden products shown in search result

**What happened instead?**

I saw hidden products

* OS & version: n/a
* Node version (node -v) [Node v4+ is required] : latest
* FoundationPress version (see line 3 in package.json): 2.7.1
* Foundation version (see dependencies in package.json) : n/a

The search needs changing, heres what I'm currently using as a custom function to get around this issue for now until I have more time or when someone else can fix:

```
/* Prevent Hidden WooCommerce products from showing up in WordPress search results */
if ( ! function_exists( 'hidden_search_query_fix' ) ) {
  function hidden_search_query_fix( $query = false ) {
    if ( ! is_admin() && is_search() ) {
      $query->set( 'tax_query', array(
      'relation' => 'OR',
      array(
        'taxonomy' => 'product_visibility',
        'field'    => 'name',
        'terms'    => 'exclude-from-catalog',
        'operator' => 'NOT IN',
      ),
      array(
        'taxonomy' => 'product_visibility',
        'field'    => 'name',
        'terms'    => 'exclude-from-catalog',
        'operator' => '!=',
      ),
      ));
    }
  }
}
add_action( 'pre_get_posts', 'hidden_search_query_fix' );
```

Cheers!

**Comment by colin-marshall** [comment]
Apparently this is always an issue when you return WooCommerce products in a search outside of the WooCommerce loop. This is because the "hidden" status of a post is unique to WooCommerce and is not recognized in WordPress core.

We could start putting all WooCommerce related functions in a new file at `/library/woocommerce-support.php`. We could wrap all of the functions in that file a conditional that checks if WooCommerce is activated so that they are only loaded when the site is using WooCommerce. The special WooCommerce sidebar I suggested in #1057 could also go in this file so it doesn't appear if WooCommerce is not installed and activated.

**Comment by Eccola** [comment]
@colin-marshall, the _s theme takes this approach: https://github.com/Automattic/_s/blob/master/inc/woocommerce.php

**Comment by olefredrik** [comment]
Is this still an issue?

**Comment by colin-marshall** [comment]
@olefredrik after thinking about this further, I don't think this change should be added to the framework. I don't see any similar functionality in starter theme [_s](https://github.com/Automattic/_s/), or even in the "full-blown" [Storefront](https://github.com/woocommerce/storefront) theme, which is the official WooCommerce theme.

Further, modifying the search query will degrade performance. Source: https://github.com/woocommerce/woocommerce/issues/12308#issuecomment-259929437

Since a small percentage of people using FoundationPress will also use WooCommerce, it would degrade search query performance with zero benefit for the majority of our users. The best solution for us is to exclude it from FoundationPress and advise people to use search query modifying plugins or add their own function to their project.
