### ISSUE TITLE
Stick with 2.9 or tweak 2.10 for compatibility?

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1075]
I am new-ish to FoundationPress and have a few projects running on version 2.9 . It is rock solid and I have had an overall great time with it.

I feel that I will need to support IE9 for a little bit longer. I can't be the only person needing to do this (or can I be?). Would you suggest sticking to version 2.9 as it is still a great starter, or go with 2.10+ and making the needed changes each new project to the template files to use the float grid? I know the refactored a lot of the JS in the new Foundation version, so maybe the gains here would be worth it.

Also, I apologize if this is not the appropriate place to ask these type of questions. Is there a forum of some sort where general questions are asked? Thanks.

**Comment by olefredrik** [comment]
The main difference between 2.9 and 2.10.x is flexbox support. IE9 does not support flexbox, but you can still use the good old float-based foundation grid in the latest version of FoundationPress. You will the need enable the foundation-grid and foundation-float-classes in your app.scss. You will also need to modify the layout classes to use the old syntax instead of the xy-grid (that is based on flexbox).
