### ISSUE TITLE
Removing before and after hooks...

### ISSUE THREAD

**Issue by JPOak** [olefredrik/FoundationPress#1097]
@olefredrik @colin-marshall Working through some refactoring of things. What do you think of removing all the hooks for before and after content, comments, etc.? Are people using these at all? Taking them out makes things look a lot cleaner and possibly easier to upkeep.

**Comment by colin-marshall** [comment]
I personally don't use them but others might. @olefredrik I would like to hear your opinion on this and also could you please add a "feedback wanted" label so we can hear from others on this? Thanks!

**Comment by dantahoua** [comment]
I never had to use them... Most of the time I let them here, but...

**Comment by FlatspinZA** [comment]
I've actually used these on my business website - they're really handy. I don't know why you would remove a core feature of Wordpress?

**Comment by olefredrik** [comment]
I agree with @FlatspinZA . Don't think we should remove it as it's a core feature of WordPress that some people find handy.

**Comment by colin-marshall** [comment]
@FlatspinZA @olefredrik we're not talking about removing a core feature of WordPress. We're talking about the FoundationPress specific hooks like `do_action( 'foundationpress_post_before_entry_content' )`.

It makes more sense to me to just edit the template files with whatever you want to put before or after the content instead of writing functions that use hooks to echo out html elements. You get a clearer picture of what's going on in the template that way. I also see no similar hooks in underscores.

**Comment by olefredrik** [comment]
Hooks are a WP core feature, although the FoundationPress spesific hooks is not. I'm sure there are many like us that thinks it makes more sense to just edit the template files instead of using hooks in functions. I feel the same way. 

But I'm not 100% sure if it's cool to simply remove the hooks, if people find it useful. The Genesis Framework [uses hooks](https://wpsites.net/wordpress-themes/new-genesis-2-0-loop-hooks-how-to-use-them/). Underscores doesn't.

**Comment by ChrisAynesworth** [comment]
I just used this specific hook in a current project today. I guess people can make any hook they like when needed, but I like this one because I can target just before the content.

Maybe it is more about those that like a theme where most of the changes reside in the functions.php file. Others, like Colin, prefer to view each template file with special content inside. I  can see the benefits of both. If people know how to use a hook, they probably know how to add one...

**Comment by JPOak** [comment]
Doesn't Wordpress already have hooks built in where you can put html snippets before and after things like the_title and the_content?

I think Underscores is a pure "starter"  theme. So, it is very barebones. Where something like Genesis is often used with a child theme, so it has a lot of stuff in it.

I guess it just depends the direction you want to take FoundationPress. I come from roots/sage where I think they take glee in eliminating things from the template files.

It's all good.

**Comment by colin-marshall** [comment]
Good feedback so far guys, keep it coming.

@olefredrik for Genesis they make sense because people build themes on top the of the Genesis Framework. We're not a framework per se. Also, it seems to me that a lot of themes that have actions to hook into, actually have code in there that already uses them, whereas ours are there to use if you want to but they don't do anything without you adding a function that uses them.

@ChrisAynesworth good points. I see where it might make the code more "DRY" to only use functions and hooks. I personally would use template-parts to accomplish the same thing without functions.

Maybe a good compromise here would be to keep the content action hooks and remove the comment ones?

**Comment by JPOak** [comment]
@colin-marshall They are really all over the place. In the sidebar.php, header.php, footer.php . Basically across all template files.

**Comment by colin-marshall** [comment]
I found [this post](https://core.trac.wordpress.org/ticket/21506#comment:67) in a WP core issue discussion very interesting/relevant, specifically:

> I was one of the original theme authors to pioneer the use of template hooks. They were meant to solve one problem: Allow theme users to add stuff into a parent theme because WordPress did not allow child themes to overwrite templates. Now, with the ability to overwrite templates and the get_template_part() function, template hooks are becoming rather useless.

So it looks like @JPOak is correct that template hooks were meant for child themes, and 5 years ago they were essentially declared obsolete by the guy who came up with them.

Now if somebody wants to use hooks over `get_template_part()`, that's their choice, but I'm all for the leaner is better approach to a starter theme. And as @ChrisAynesworth pointed out already,

> "If people know how to use a hook, they probably know how to add one..."

**Comment by olefredrik** [comment]
Actually I was not aware that hooks were meant for a parent / child theme setup. FoundationPress was never meant to be a parent theme, but a plain starter-theme that people can use directly as a starting point for new projects. I agree with your arguments to remove the hooks. If we do, I suggest we remove both the content and comment hooks. Feel free to create a pull request :)

**Comment by FlatspinZA** [comment]
Well, then, @colin-marshall - you have made your point. Probably me just being lazy-ass. :P

**Comment by JPOak** [comment]
@colin-marshall  @olefredrik Does this mean we can we move them from the entire theme? Including in the header.php, sidebar.php, footer.php and everywhere else? If so, i’ll do the PR . I’ve been wanting to do this since I first used FP.

**Comment by colin-marshall** [comment]
@JPOak yes I believe it's ok to remove all hooks you mentioned.

**Comment by Aetles** [comment]
I'm late to this, but thank you @JPOak! In my own forks I've removed all these hooks long ago but they still haunt me every time i diff for changes, so I'm very happy they are gone! 👍

**Comment by JPOak** [comment]
@Aetles Yes. It was a good time.
