### ISSUE TITLE
Post Image Aligment

### ISSUE THREAD

**Issue by bgajus** [olefredrik/FoundationPress#110]
The align attribute does not appear to be getting added to a post image.

**Comment by Jastos** [comment]
For anyone still having this problem here is what I did:

Removed the entire Clean up image tags section from cleanup.php
Commented out additional post related cleaning
// add_filter('get_image_tag_class', 'image_tag_class', 0, 4);
    //add_filter('get_image_tag', 'image_editor', 0, 4);
    //add_filter( 'the_content', 'img_unautop', 30 );

This will give you:
<div id="attachment_191" style="width: 160px" class="wp-caption alignleft">

This has removed HTML5 support for <figure> and has an absolute width assigned which breaks responsive.

Add back in HTML5 support in functions.php:
add_theme_support( 'html5', array( 'gallery', 'caption' ) );

This leaves you with <figure> tag but still set width which breaks responsive:
<figure id="attachment_191" style="width: 150px;" class="wp-caption alignleft">

Remove inline width from figure element. I stole the code from here:
https://stackoverflow.com/questions/23812072/wordpress-3-9-x-remove-inline-width-from-figure-element/24755913#24755913?newreg=08ded3b2a5f74a3887516382e7cc6527

Use the MarkLL solution. Careful he named his functions wrong in the Hook, so be sure to make them match.

You should now have a max-width instead of width:
<figure style="max-width: 540px;" class="wp-caption alignright">

**Comment by magicjoef** [comment]
Hi, I've also had problems with images in posts. Jastos, I've used most of your approach, by removing the image cleanup section and adding HTML5 support back in via functions.php.

I wasn't too keen on the PHP fix for changing the inline style (bit over my head) so instead I've just used a CSS !important override on the figure tag in my CSS. I know it isn't ideal, but it is working at the moment.

Is there an official fix for the image alignment? Other than that everything seems to work great in this theme, thank you!

**Comment by alexpetroni** [comment]
Hi, the problem reside in https://github.com/olefredrik/FoundationPress/blob/master/library/cleanup.php#L181 , function recreate_img_tag( $tag ) . 
	        if ( in_array( $class_segs[0], $allowed_classes ) ) {
	          $img .= ' class="' . $class_segs[0] . '"';
	        } 
If the image has class="  size-medium wp-image-841 alignleft" (view the space after quotes), it will compare empty string to allowed class. 

Correct would be 	        if ( $filtered_classes = array_intersect( $class_segs, $allowed_classes ) ) {
	        	$img .= ' class="' . implode(' ', $filtered_classes) . '"';
	        }

**Comment by olefredrik** [comment]
Good find, @alexpetroni ! Feel free to send a pull request for your fix.

**Comment by phylaxis** [comment]
I have a new issue related to this original bug. With this filter in place you lose the ability to set classes on images per post using the Advanced image settings 'Image CSS field'. Is there a way to get that functionality back? I could add the classes I want to the `$filtered_classes` array, but that is not very practical.

**Comment by alexpetroni** [comment]
Hi Ole,

The role of this filter is to remove all the style classes that are not in
the "align(left|right|center)" OR "size-(full|medium|thumbnail)" format.
The solution for accepting custom classes is to suppress the filter.
Personally I don't understand why this filter is necessary, it removes even
the "wp-image-number" class, which doesn't hurt anyone.

Hope it helps.

Best wishes,
Alex

On Wed, Jan 20, 2016 at 9:05 AM, Adam Christianson <notifications@github.com
