### ISSUE TITLE
FoundationPress cloned site doesn't run build/run watch

### ISSUE THREAD

**Issue by cdriscoll66** [olefredrik/FoundationPress#1143]
Hi, any help would be appreciated. 

We have a back up that was cloned and the cloned site doesn't compile - It doesn't allow us to run any commands - 

[npm-debug.log](https://github.com/olefredrik/FoundationPress/files/1440936/npm-debug.log)

**Comment by colin-marshall** [comment]
@cdriscoll66 please fill out the issue template so we can assist you.

**Comment by marcoValkyriweb** [comment]
Have you installed node js?
"Make sure you have the latest version of node.js and npm installed." from the error sheet.
Get NodeJS from here: https://nodejs.org/en/download/
Then run npm install in the root folder of the theme.

Personally I prefer downloading chocolatey and using that to install: https://chocolatey.org/docs/installation which is a package manager.

Once installed, you run `choco install nodejs.install`.
I also prefer using yarn over npm, it compiles code faster, around 6 seconds reduction for me on production build, 8s versus 14s using normal npm/gulp.

To install yarn, just run `choco install yarn`. Then in the root folder, instead of running npm install, you can just run `yarn` which will install all the required dependencies, also arranging them properly for faster speeds. If you have used npm install instead, don't worry, you can still just use yarn, it will rearrange the packages and you'd be good to go.

To run npm/yarn during development, use npm start or yarn start depending on which you'd like to use. For staging/live, use npm build --production or yarn build --production.
