### ISSUE TITLE
FoundationPress not being uploaded to GIT

### ISSUE THREAD

**Issue by jinalLN** [olefredrik/FoundationPress#1217]
Hello,

I have downloaded FoundationPress theme and it's child theme to my local ubuntu PC. I have set up that theme using a command line. 

Now I want to move whole WordPress website to my local GIT repository. But when I try to push them to GIT, FoundationPress parent theme doesn't get uploaded. 

What could be the reason behind this? 

Thanks
JLN

**Comment by taugerbeck** [comment]
Hi JLN,
I would suppose that this is a git issue. Did you follow the description on how to fork/clone a repo (and attach the upstream repo)? see https://help.github.com/articles/fork-a-repo/
"Downloading and copying files" is not the git way... 

Regards,
Ralf

**Comment by colin-marshall** [comment]
@taugerbeck is correct, you should fork the repo, but I think the problem you are having is related to git submodules. If I'm understanding correctly, you have created a repo for your entire WordPress directory? So that means that your FoundationPress directory is a git repo inside of another git repo. FoundationPress is now a submodule of the other git repo. 

Unfortunately I don't have much experience with submodules, but I'm sure you can find the info you need by googling.

**Comment by jinalLN** [comment]
@taugerbeck I have cloned git REPO to my Wordpress folder. 
@colin-marshall  yes you are correct. I have a Wordpress setup on my local computer. And inside the theme folder, I have Cloned FoundationPress and FoundationPress child. 

Now I want to push whole Wordpress Directory to GIT. But it's creating a problem with me.

**Comment by colin-marshall** [comment]
@jinalLN FoundationPress is not made to be used with a child theme.

**Comment by jinalLN** [comment]
@colin-marshall okay, I see. So if I want to create a theme for the Wordpress, I need to create it using FoundationPress Main theme right?

**Comment by colin-marshall** [comment]
FoundationPress is a starter theme so you want to fork the repository, then clone your fork locally. Then you customize it to your needs.

**Comment by colin-marshall** [comment]
@jinalLN did you get this resolved?
