### ISSUE TITLE
Not an issue (sorry) but can someone help me understand this

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#1292]
I'm trying to customise the responsive image for content, but struggling to wrap my head around this

```
	// Full width page template
	if ( is_page_template( 'page-templates/page-full-width.php' ) ) {
		if ( 1200 < $width ) {
			$sizes = '(max-width: 1199px) 98vw, 1200px';
		} else {
			$sizes = '(max-width: 1199px) 98vw, ' . $width . 'px';
		}

```

So its saying If the window size is greater than 1200px then the image size is 98% of 1200px, but if the window size is less than 1200px the image size is 98% the width of the window?

Is that right?

**Comment by colin-marshall** [comment]
@nitrokevin this is sort of confusing because we're talking about the width of the image AND the width of the viewport. The `$width` variable refers to the width of the image, not the viewport.

So the first part of the conditional is saying if the image is wider than 1200px, at the media query of `(max-width: 1199px)` the image should be 98% of the viewport width. If it doesn't match that media query, the width of the image will be set to 1200px.

The `else` part of the conditional is the same as above, except instead of setting the width to 1200px when it doesn't match the media query, the size of the image is set to the actual width of the image.

This article explains it pretty well:
https://viastudio.com/optimizing-your-theme-for-wordpress-4-4s-responsive-images/

**Comment by colin-marshall** [comment]
Closing this out, feel free to reopen if you need more help.
