### ISSUE TITLE
Login Box

### ISSUE THREAD

**Issue by DesignTheBox** [olefredrik/FoundationPress#141]
Hi Unsure if this is the correct place to comment but i have the foundationpress theme and when i go to login if i put the wrong password or user name the error box does not display the text

**Comment by groovenectar** [comment]
Why not make that an option, or ship it commented out? It can be confusing when common login behavior is changed. It appears that something is going wrong, since the error box still shows but is blank... It might be neat if the error box is removed entirely, and only the login box shaking stays, but I still don't see a huge security concern to inform the user about mistyped login...

**Comment by olefredrik** [comment]
@groovenectar : I agree. Fixed https://github.com/olefredrik/FoundationPress/pull/350
