### ISSUE TITLE
Don't load jquery 2.x for IE 8

### ISSUE THREAD

**Issue by AdamChlan** [olefredrik/FoundationPress#178]
I'm using conditional code in my header.php file to load jquery 1.x and a few other files for IE 8. This works very well for making the foundation play nicely in IE 8. I'd also like to NOT load jquery 2.0 if on IE 8, which is loaded in enqueue-scripts.php. Has anyone hidden this file conditionally for IE 8, or have any advice on the best way to do it?

**Comment by versedi** [comment]
I'm personally using
```
<!DOCTYPE html>
<!--[if IE 7]>
<html class="no-js ie ie7" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 8]>
<html class="no-js ie ie8" <?php language_attributes(); ?>>
<![endif]-->
<!--[if IE 9]>
<html class="no-js lt-ie10" <?php language_attributes(); ?>>
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
```

**Comment by themestechnology** [comment]
From my understanding foundation uses rem size measurement that is not
supported in IE7 and IE8 so would there be any point using that code?

http://caniuse.com/#search=rem

Also $_SERVER['HTTP_USER_AGENT'] could be used to detect detect the device
browser rather than it appearing in Firefox and Chrome



Best Regards

Phill Booth. Theme Tec

*Please remember add my email to your address book.*

*web:* http://www.themes.technology

*email:* help@themes.technology <help@fthemes.technology>

*portfolio*: http://themeforest.net/user/phillbooth/portfolio?ref=phillbooth

*time zone:* GMT+0 London, United Kingdom

**Comment by versedi** [comment]
There's a way for that:
https://github.com/chuckcarpenter/REM-unit-polyfill
http://foundation.zurb.com/forum/posts/241-foundation-5-and-ie8

**Comment by Aetles** [comment]
FWIW last year when I was trying different REM polyfills to make Foundation 5 layouts work in IE 8 I ended up using grunt-pixrem instead as it work much better for me.

**Comment by andreaarcher** [comment]
I'm trying some conditional logic in my enqueue-scripts.php to get a certain js to not load in ie11 only,
I'm using
```
if(preg_match('/(?i)msie [11]/',$_SERVER['HTTP_USER_AGENT']))
    {
        
         wp_enqueue_script( 'foundation', get_template_directory_uri() . '/assets/javascript/foundation.js', array('jquery'), '2.3.0', true );

    }
    else 
    {
         wp_enqueue_script( 'foundation', get_template_directory_uri() . '/assets/javascript/foundation.js', array('jquery'), '2.3.0', true );

        wp_enqueue_script( 'wow', get_template_directory_uri() . '/assets/javascript/wow.js', array('jquery'), null);
    }
```

but it's not working -- both files are still loading on ie11. Any ideas?
