### ISSUE TITLE
Stick footer to bottom when page is empty

### ISSUE THREAD

**Issue by dantahoua** [olefredrik/FoundationPress#196]
Hello.
Did someone manage to stick the footer to the bottom when a page is empty... The .off-canvas-wrap block us to to do that...
This code do not work:
html,body{
	height: 100%;
}
.off-canvas-wrap{
	min-height: 100%;
}
.inner-wrap{
	min-height:100%;
	position:relative;
	padding-bottom: 240px; //The height of your footer
}
#MainFooter{
	min-height: 240px;
	position:absolute;
	bottom:0;
	left: 0;
	width: 100%;
}
Note that if I use min-height: 100vh; for the inner-wrapper it's working (but sadly not in every browser).

Here is the simplified html structure (same as FoundationPress) :
<body>
<div class="off-canvas-wrap" data-offcanvas>
	<div class="inner-wrap">
	<footer id="MainFooter">
	<?php do_action('foundationPress_before_footer'); ?>
	<div class="row">
		<?php dynamic_sidebar("footer-widgets"); ?>
	</div>
	<?php do_action('foundationPress_after_footer'); ?>
</footer>
        </div>
</div>
</body>

**Comment by themestechnology** [comment]
For myself I have a bespoke breadcrumb and have placed my footer just above the <footer class="row"> in footer.php and does not require any CSS 

<section class="show-for-medium-up row">
<ul class="breadcrumbs small-12 medium-12 large-12 columns"   >

**Comment by Aetles** [comment]
I have used the [foundationStickyFooter](https://github.com/coreysyms/foundationStickyFooter) although I had [issues](https://github.com/coreysyms/foundationStickyFooter/issues/6) with Foundations use of 100% height on body (which I never got a satisfying answer to [my question](https://github.com/zurb/foundation/issues/4474#issuecomment-44011766) of why it was needed). Anyway, the developer of foundationStickyFooter said he changed the code to make it work even with 100 % height on body so that should not be an issue any more.

**Comment by dantahoua** [comment]
Finally I mange to do it by moving the footer outside the "inner-wrapper" but keep it inside the "off-canvas-wrap". It's working perfectly, no need of js...
