### ISSUE TITLE
Sourcemap not working

### ISSUE THREAD

**Issue by linuxbastard** [olefredrik/FoundationPress#199]
I thought I may have done something wrong so I installed a fresh theme on a dev site and I can see the sourcemap file and see the comment for it at the end of foundation.css but Chrome (40.0.2214.91) Devtools refuses to use the map. I've also mapped my local workspace still nothing.

And I don't know if this is related, but do I need the scss files on the server? If I do not include the 'bower_component' folder I get a ton of 404s for some reason. I see it on the FoundationPress site too (http://foundationpress.olefredrik.com/).

**Comment by themestechnology** [comment]
Could you have a browser plugin that is blocking scripts you should not get and 404's.

**Comment by jmbarlow** [comment]
You have to have the bower_components folder available on the server, as that's where it looks for the sourcemaps:If you look at the demo site, the value appended to the end of the CSS file is:

```
/*# sourceMappingURL=foundation.css.map */
```

and this is what that [sourcemap](http://foundationpress.olefredrik.com/wp-content/themes/FoundationPress/css/foundation.css.map) looks like:

```
sources: [
"../scss/foundation.scss",
"../scss/_normalize.scss",
"../scss/config/_settings.scss",
"../scss/assets/_icons.scss",
"../bower_components/foundation/scss/foundation/components/_grid.scss",
"../bower_components/foundation/scss/foundation/components/_accordion.scss",
"../bower_components/foundation/scss/foundation/components/_alert-boxes.scss",
etc.
```

So if it can't find those bower_components, you're not going to get source mapping.

**Comment by linuxbastard** [comment]
OK got that, but even with the bower_components folder up on the server source mapping still is a no go on my end. I thought maybe some chrome extension was causing it but I disabled all my extensions and still nothing.

**Comment by jmbarlow** [comment]
@linuxbastard I should also clarify that you are correct: Sourcemaps are not working in libsass.  See: [bug report in libsass](https://github.com/sass/libsass/issues/837). They reckon it'll be sorted in Libsass 3.2.

In the interim, you could use SASS, or grunt-contrib-sass  (instead of grunt-sass) if that makes sense.

**Comment by olefredrik** [comment]
I don't know what workflow you have, but in my world you would typically need source mapping only on your local dev environment. Obviously all scss files are available locally, but I would not push these into production. The same applies to bower_components files, as all the good stuff will be concatinated and minified to foundation.js and foundation.css on grunt build.

@jmbarlow is correct that source maps are not working in libsass due to a bug. Waiting for a bugfix in version 3.2.
