### ISSUE TITLE
Error: Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by prwilcox** [olefredrik/FoundationPress#217]
Hello,
I'm attempting to work with a preprocessor for the first time. I believe I have successfully installed node, grunt, and bower. After navigating to my FoundationPress theme folder and running the grunt watch command the terminal says the following:
Loading "sass.js" tasks...ERROR
>> Error: Cannot find module 'node-sass'

Running "watch" task
Waiting...

Any advice on how I can avoid receiving the error would be greatly appreciated. Thanks!

**Comment by themestechnology** [comment]
https://github.com/olefredrik/FoundationPress/issues/208#event-234870812

**Comment by prwilcox** [comment]
When I run $ npm install && bower install && grunt build I get an error saying node scripts/build.js fails on your system.

**Comment by prwilcox** [comment]
I tried running each command separately. After installing a program called Xcode $ npm install appeared to run successfully. When I ran $ bower install I received the following error:
Loading "sass.js" tasks...ERROR
>> Error: Cannot find module 'node-sass'
Warning: Task "sass" not found. Use --force to continue.

Aborted due to warnings.

**Comment by themestechnology** [comment]
Install node http://nodejs.org/

and insatall scss

**Comment by olefredrik** [comment]
Hi,

First make sure you follow the requirements and quickstart steps described in the howto.

If you can't get it working after following these steps, it's possibly because the node-sass package is incompatible with the latest version of node.

Please see my post in this thread (https://github.com/olefredrik/FoundationPress/issues/209) for a solution on how to roll back to node v. 0.10.33
