### ISSUE TITLE
Is there a 'best' way to set up 

### ISSUE THREAD

**Issue by joshsmith01** [olefredrik/FoundationPress#230]
Is there a best way to set up sidebars with widgets in FoundationPress? I am struggling to find the correct layout. 

Do I set the widgets-areas.php to add the rows or widths or do I add them to each widget?

**Comment by sky1tech** [comment]
Depends on where you want them to display. The widget-areas.php file simply registers the sidebars (Right and Left) so that boxes on the Widgets page (under Appearance) will show up so you can drop widgets there manually.  

If you want them to display on a page, you select the Default Template (Right Sidebar) or Left page template under Templates while editing a page. Review the code in those templates to see what's going on. 

The page template files with sidebars are page.php (Default Template) and page-sidebar-left.php (Left Sidebar)

Left sidebar uses this call
<?php get_sidebar('left'); ?>

Right sidebar uses this:
<?php get_sidebar(); ?>

Then go review the code in sidebar.php to see what's going on. 

After you study the markup, go see Foundation's docs to determine how to make changes with the display. 

Hope this helps...
