### ISSUE TITLE
[question] where to place custom SCSS files?

### ISSUE THREAD

**Issue by tconroy** [olefredrik/FoundationPress#235]
Hey there,

The documentation states,

> * `scss/foundation.scss`: Imports for Foundation components and your custom styles.

What is the optimal/default location to place my custom .scss files? Should I place them directly into the `bower_components/foundation/scss` folder? wouldn't they be overwritten if I update Foundation in the future? What is the proper location?

Thanks! great work by the way :-)

**Comment by Endlyss** [comment]
Personally, I use the site folder.

scss/foundation.scss

When you open that file, there is a place at the bottom that says
/* 
  My custom styles:
  Add your own folders and scss files for your project and import them below
*/ 

You can place your files anywhere that you feel is most optimal, and then just use @import and a relative path to access it, below that comment area. 

I do everything directly in the scss/site folder since it is right there at the foundation.scss

**Comment by tconroy** [comment]
Ahh, I was looking in the wrong foundation.scss file, that explains it. I think I'll follow your lead and keep mine in the `scss/site` folder as well, thanks.
