### ISSUE TITLE
Get typeerror when I tried to use foundation tabs or accordions

### ISSUE THREAD

**Issue by lisettemariabustelo** [olefredrik/FoundationPress#259]
Seems to work fine until page load and then throws errors when I try to click the tab and does nothing.

**Comment by olefredrik** [comment]
There was an error with the accordion that was fixed in a pull request 19 days ago: https://github.com/olefredrik/FoundationPress/commit/c84a7528923b7ce33bd6423059488cab47cb33cb

Please pull the latest version and do a ```grunt build```. I have verified that this works as demonstrated on http://foundationpress.olefredrik.com/kitchen-sink/
