### ISSUE TITLE
How do you implement code into your WordPress pages?

### ISSUE THREAD

**Issue by dfill** [olefredrik/FoundationPress#267]
Hey everyone,

I've decided to use FoundationPress for a Starter Theme. I had one quick question about developing with Wordpress and Foundation.

Usually when I handcode a site, I literally handcode all the content in Sublime Text and that's that. For WordPress, do I handcode all of the content in a text editor and then dump it into the WYSIWYG editor of WordPress? Or is there another way?

One of the reasons of using WordPress is that so clients can go in without my help (or knowledge of code) and adjust things. How does this play in?

Any help would be great!

**Comment by joshsmith01** [comment]
The WYSIWYG editor in WordPress is built for adding content. If I were you, I would not write content in a text editor just to then just copy and paste it into WordPress. 

Use the WYSIWYg. It has a similar look and feel that MS Word has so it is familiar to a clients. You also have versions and drafts so it's not like you can take your time on the blog post or page content or whatever.  If you need to add HTML, you can switch the tab from Visual to Text. By the way, in WordPress it's called the Visual Editor.

**Comment by tnog** [comment]
I would strategize on what content areas are static and what's going to be
dynamically updated. You may consider just adding your HTML directly to the
template, or inserting it through a hook or filter, depending on the
location or purpose. If the content is static and will not need to be
changed at all over time, it will probably be more efficient to just add it
that way rather than having it stored in the database.

FYI: I hardly ever use WP's inbuilt WYSIWYG editor. If I need to markup
some more complex HTML to insert in a page or post it's far easier to use
Sublime Text. Otherwise, maybe use a Markdown plugin

-----------
Takahiro Noguchi
ph: +1 510.213.8252
skype: takahiro.noguchi

"...seek and learn to recognize who and what, in the midst of the inferno,
are not inferno, then make them endure, give them space."

         ~Italo Calvino, from "Invisible Cities"

**Comment by olefredrik** [comment]
Looks like you've got good answers to your question already. Add content in the WYSIWYG editor. Define the structure and content zones in your template files. Would recommend using Advanced Custom Fields (ACF) to define content zones in your templates.
