### ISSUE TITLE
top-bar

### ISSUE THREAD

**Issue by Tonzr** [olefredrik/FoundationPress#277]
I'm helping my sport club with a new website based on FoundationPress but I got a problem that i can't figure it out and I'm hoping that someone will lend a hand.

It is about the top-bar, is it possible to make it look like the one here on this website http://bit.ly/1FvvsLs with an "open" horizontal submenu? If someone can point me in the right direction it will be awesome and I will be very grateful!

**Comment by aroncreative** [comment]
I'm not sure there is a value in adding this sort of functionality to foundation press. The top-bar is likely to be re-written in the upcoming Foundation 6 release by zurb. Since FoundationPress is a WordPress port of Foundation differentiating drastically from Foundation doesn't make sense.

If you need this functionality now you'd be better off adding a separate javascript or css MegaMenu into your existing code. A MegaMenu is currently on the list of possible additional features to be added in Foundation 6, if interested you can add to the conversation or vote for the feature here: https://trello.com/b/QBPKlQqf

Also Included in that discussion is a link to a MegaMenu that might work for you: http://codyhouse.co/demo/mega-site-navigation/index.html
