### ISSUE TITLE
Editing sass with CodeKit problem

### ISSUE THREAD

**Issue by bpinet** [olefredrik/FoundationPress#287]
Hi there, 
it's a great tool you've built. I have problem with sass. Whenever I edit _custom_setting.sass or other files after compiling page breaks and only overwriting original foundation.css help. It looks like all styles disappears.

I'm new into this, so forgive me silly questions. In your package bower components are missing but those files are marked for import in files. Am I missing something?

**Comment by olefredrik** [comment]
Hi,

If you [look at the requirements](https://github.com/olefredrik/FoundationPress#requirements), you'll see that you will need to have node, grunt and bower installed to use this theme. 

That said, should be possible to use Codekit with FoundationPress but it is not officially supported since I have little experience and knowledge with it. 

Here are a few links that could be helpful to you:
http://justinklemm.com/grunt-watch-livereload-javascript-less-sass-compilation/
https://github.com/fatso83/grunt-codekit

Cheers,
Ole Fredrik
