### ISSUE TITLE
Breakpoints for the top-bar toggle

### ISSUE THREAD

**Issue by Norm101** [olefredrik/FoundationPress#291]
Pardon me if I'm not explaining this very well.

There is a problem with the breakpoint for the top-bar toggle.  There is a range between where the off-canvas menu icon appears and where the main menu appears.  The menu-icon (the burger) should show up as soon as the main menu toggles away, but it doesn't until the screen width is much smaller.

It appears to be a common problem with Foundation, but the solutions I've found on the forums don't seem to work with FoundationPress.  I've changed the media queries but it has no effect on the js.

http://foundation.zurb.com/forum/posts/1053-changing-topbar-breakpoint-using-css

**Comment by olefredrik** [comment]
Hello. Ideally, we would have a dynamic breakpoint calculated, based on the width of the menu contents at any time. This would however be a complicated affair that would require a slight portion of javascript in order to work. There is a reason why this isn't already a part of the Foundation core. 

Anyway, I've managed to come up with a solution that allows you to set a custom breakpoint value deciding when the topbar visibility should be switched with the mobile menu. Please see this pull request for details: https://github.com/olefredrik/FoundationPress/pull/323 .

The [FoundationPress demo site] (http://foundationpress.olefredrik.com) is now updated with the topbar breakpoint fix. (You may need to delete your cache to get the latest css).
