### ISSUE TITLE
Recommended Portfolio plugin that plays well with FoundationPress?

### ISSUE THREAD

**Issue by jdfweb** [olefredrik/FoundationPress#295]
Hi all!

A client of mine would like to use a portfolio within their website. What's the best, filterable portfolio plugin that you've come across that integrates well within FoundationPress?

Thank you in advance.

**Comment by Eccola** [comment]
Hi,

if you know how to make a unique theme out of FoundationPress, I would like to suggest you create a custom post type for your portfolio objects, choose your visual approach (jQuery), and create custom, context-aware loops for your portfolio content, which you can then style to your design. You could even use some Foundation components for your portfolio display!
IMHO, forget those wordpress org plugins, they're bad for you and your design.

**Comment by jdfweb** [comment]
Hi @Eccola !

I know how to add custom post types through a plugin, how do I create custom, context-aware loops for my portfolio content?

Any help would be appreciated!

**Comment by Eccola** [comment]
Hi jdfweb,
glad you asked,  coding the features yourself, you always have the control of everything to yourself!
FoundationPress is a developers dream, now you really can code premium quality themes for your clients out of it, in no time. You have a working dev environment? Use Grunt?

So, I just finished a portfolio/blog site a couple of weeks ago at http://stormarts.fi and had a great success with Justified Gallery: http://miromannino.github.io/Justified-Gallery/ with Swipebox. Everything here is done on FoundationPress. There is still no image optimization, this is photographers site, and you know they want to crop their images to exotic proportions and usually there's no image compression used before uploading. Kinda heavy image-wise, otherwise very light.

You better get started, so here's a basic loop and a page template for FoundationPress which outputs your portfolio objects into F5 block-grid:
https://gist.github.com/Eccola/05616be9b0b3117c92e8

More: http://foundation.zurb.com/docs/components/block_grid.html

Must read: http://www.billerickson.net/code/wp_query-arguments/
for your object filtering tasks.

Just update/add the arguments to your needs.

Create your custom post type with title, editor, thumbnail, excerpt, whatever to your needs, you can even attach some neat custom fields to them, if you like. Use taxonomies, tag your objects, or categorize them. Create new taxonomies if needed.

Create a page named Portfolio or something and use the portfolio.php template, add some portfolio objects, attach featured images to them and see how they populate the Portfolio page. Now, styling is a breeze with FoundationPress.

If you for some reason want to ditch block-grid, you could easily update the output to your new syntax.

That's the basics of looping, what do you think? 
There's more, just ask :)

**Comment by olefredrik** [comment]
I share @Eccola 's view of using third-party plugins. Many of the plugins out there are less good in quality, unfortunately. There is however one plugin that I would always recommend. [Advanced Custom Fields](http://www.advancedcustomfields.com/). Check it out!

@Eccola . Nice work on Storm Arts! Looks great! Would you mind if I add a link to your site from the 'selection of sites using FoundationPress' section on the front-page of the FoundationPress repo?

**Comment by olefredrik** [comment]
@jdfweb : I used the Advanced Custom Fields plugin with the Repeater Field add-on for my own portfolio http://olefredrik.com (yeah, I know it's very basic).

**Comment by Eccola** [comment]
@olefredrik , it would be an honor to be added to the selection!

**Comment by LukePettway** [comment]
ACF is definitely how I would do it as well.

**Comment by metavurt** [comment]
I'm gonna +1 on ACF as well - it's literally been one of the few plugins that does exactly what I need without bogging down (or worse, conflicting with) any WP install and theme combination that I'm using. This is includes, but isn't limited to, FP. I am *not* associated with ACF in any way, so when I say that it's really the best one I've used to tie various site components together and not muck up my grid, I really truly mean it.
