### ISSUE TITLE
FoundationPress + Shared Hosting?

### ISSUE THREAD

**Issue by robycris** [olefredrik/FoundationPress#305]
Hi guys,

I am new to FoundationPress. However, I am very interested in learning the magic.
My question is... Is it possible to install FoundationPress on a shared hosting environment? The reason why I ask, is because the plugins seem to fail.

Currently, I use MDD Hosting solutions. However, I do not believe I have access to Grunt. Is there anything I can still do?

Thank you very much!

Cheers,

Robin

**Comment by olefredrik** [comment]
Hi Robin,

I don't know what workflow you are using from day to day, but I would recommend that you develop locally (using a local webserver such as MAMP/LAMP for mac/linux or WAMP for windows) and deploy the project to a server when it's finished. It's only on your local dev environment that you will enjoy the benefits of Grunt and Sass anyway. The project that you deploy to your server will be optimized and minified without using all the dev dependencies (node_modules, bower_components and so on). 

That was the long answer. The short answer to your question is: yes. You will not need to access Grunt on a shared hosting solution, as long as you do your web development on your localhost. In fact, you don't need to use Grunt og Sass at all. But I really recommend that you spend some time reading up on it, because it will make your life easier.

I've made a quick video tutorial on installing FoundationPress. It's available on YouTube https://www.youtube.com/watch?v=s4m5wwM4BWM 

Good luck and have fun :)

Cheers,
Ole Fredrik
