### ISSUE TITLE
Top Bar Navigation not showing in 796px width or below.

### ISSUE THREAD

**Issue by marvinsss2005** [olefredrik/FoundationPress#318]
Hi,

When the width reach 796px or below the top bar navigation is gone and covered by the homepage-hero background the same with your demo site http://foundationpress.olefredrik.com.

Thanks...

**Comment by Aetles** [comment]
Yeah, it becomes hidden because `.top-bar` has a specific height and the `ul` with the navigation is pushed down when it doesn't fit. If you remove height from `.top-bar` or change it to `auto` then the top bar navigation is shown on a second line, just like it does on the [Foundations Docs](http://foundation.zurb.com/docs/) when the width is around 600 px.

**Comment by olefredrik** [comment]
Hello. Ideally, we would have a dynamic breakpoint calculated, based on the width of the menu contents at any time. This would however be a complicated affair that would require a slight portion of javascript in order to work. There is a reason why this isn't already a part of the Foundation core. 

Anyway, I've managed to come up with a solution that allows you to set a custom breakpoint value deciding when the topbar visibility should be switched with the mobile menu. The [FoundationPress demo site] (http://foundationpress.olefredrik.com) is now updated with the topbar breakpoint fix. (You may need to delete your cache to get the latest css).
