### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by adelineyaw** [olefredrik/FoundationPress#38]
I've wanted to use FoundationPress on my local server (using MAMP) and I've followed your instructions to clone this repository etc except I get the following:

"Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Is there something I'm missing?

**Comment by patrickbjohnson** [comment]
Noticing I'm getting this issue when trying to commit my project (with this starter theme) included in the repo. Any way to resolve this issue?

**Comment by olefredrik** [comment]
Which error message do you get?

**Comment by patrickbjohnson** [comment]
Here is the error message: 
```
ERROR: Permission to olefredrik/FoundationPress.git denied to patrickbjohnson.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Also note that this is a theme within a wp-project. I have a .git file at the root of the WP project, not just on the theme. But it looks like the theme (which is a clone of your Foundation Theme Starter) also has a git repo attached to it (which is your original repo). 

I can push my WP repo just fine. It looks as though it might be including the changes from the theme but not sure as its showing up as a grayed out folder (I think thats a sub-module from my googling) (screenshot here: http://cl.pbj.me/image/0z1r081R1n0A)

But if I run `git status` on the WP theme from your Foundation Theme Starter (the theme is called 'almanac') then i get this: 
```
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
```
Which is probably because I've updated it in general with my project-specific styles. But not sure why I can't gain access to that folder within my WP project.

**Comment by patrickbjohnson** [comment]
I can give you a quick confirmation that when I clone my own project (the complete WP project) the almanac folder (cloned from your Foundation Theme Starter) is not included.

**Comment by jmbarlow** [comment]
Fork Ole's repository, then clone your fork. That'll allow you to push commits to Github (the remote of your locally cloned repo). You can then offer pull requests to Ole to pull into his repo.

**Comment by patrickbjohnson** [comment]
@jmbarlow Still creates a sub-module that won't contain changes made within the repo. [See screenshot](http://cl.pbj.me/image/1L1U092y3U3H). 

'almanac' is a direct git clone with ssh from FoundationPress
'almanac-two' is a direct git clone with ssh of the forked repo of FoundationPress
'almanac-three' is a direct git clone with HTTPS of the forked repo of FoundationPress

**Comment by jmbarlow** [comment]
Personally I'd avoid using git sub modules as I've found them to be a massive pain in the arse. You must have write access to the upstream repo if you want to include that sub module in your repo. Since you don't, that's why you're getting the error.

If you want to maintain a reference back to Ole's repo, you could try sub trees instead?

http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by patrickbjohnson** [comment]
I didn't *want* to use sub modules in the first place. Not entirely sure why its set up that way? Could it be due to two different git set ups in my project? Main git = wp project, secondary git = FoundationPress

**Comment by toastdesign** [comment]
Maybe i'm at the place for asking this but this is the page that come back on every search. Im using foundationpress as my starter theme for most of my project. To push and pull changes to my repositories im using Git Tower (gui). But last months when i clone foundationpress into my themes folder it added as a submodule and im not able to do any commits. Does someone knows what this could be?

**Comment by olefredrik** [comment]
@toastdesign : When you clone the FoundationPress project from Github, the remote will point to the main repo github page by default. You can verify this by typing ``git remote -v`` when you're in the theme directory. It will look like this: 

```
origin	git@github.com:olefredrik/FoundationPress.git (fetch)
origin	git@github.com:olefredrik/FoundationPress.git (push)
```

If you haven't already, you should update the remotes to point to your repositories. More info can be found here: https://git-scm.com/docs/git-remote
