### ISSUE TITLE
foundationpress_fixed_img_caption_shortcode is being ignored

### ISSUE THREAD

**Issue by zanetaylor** [olefredrik/FoundationPress#383]
The shortcode in library/cleanup.php to replace the default WP caption HTML with `<figure>` and `<figcaption>` seems to be completely ignored by WordPress 4.2.2.

**Comment by Aetles** [comment]
I think the whole library/cleanup.php could use an overview. I'm not sure how many of the functions there are need and works, I usually end up remove some of them because they caused issues for me. Most of the code there is still the same as [the code](https://github.com/milohuang/reverie/blob/747e2c9e796a03fd7574b022ce924e540966ecf0/lib/clean.php) was in [Reverie 4](https://github.com/milohuang/reverie/tree/747e2c9e796a03fd7574b022ce924e540966ecf0) of which I'm pretty sure FoundationPress was a fork of, even though it does not say so anywhere.

**Comment by olefredrik** [comment]
You're right. The image cleanup functions was quite a mess, to be honest. Have wiped it out and replaced it with a better solution, adopted from [Brian Gottie](http://blog.skunkbad.com/wordpress/another-look-at-rebuilding-image-tags). Check this pull request for details https://github.com/olefredrik/FoundationPress/pull/384.

The demo page is now updated with a working example of an image with a caption. 
http://foundationpress.olefredrik.com/post-with-an-image-and-caption/

Feel free to tweak it further and add in ```<figure>```, ```<figcaption>``` tags and whatnot. I'm always open to look at your pull requests if you want to contribute :)

Cheers,
Ole Fredrik
