### ISSUE TITLE
Modified Grunt.js to include a deploy package command

### ISSUE THREAD

**Issue by pmccauley** [olefredrik/FoundationPress#406]
I wanted to see if you were interested in including this in your grunt build. It uses grunt-contrib-compress
It takes the name from package.json and creates a theme directory. I just run the command.

grunt deploy

 I use the ignore Glob to ignore node, bower, and whatever else is not theme related.

    //package the theme and remove folders
    compress: {
      main: {
        options: {
          archive: 'deploy/<%= pkg.name %>.zip'
        },
        expand: true,
        cwd: '.',
        src: ['**/*','!**/node_modules/**','!**/bower_components/**','!**/scss/**','!**/deploy/**','!**/bower.json','!**/Gruntfile.js','!**/package.json','!**/composer.json','!**/composer.lock','!**/codesniffer.rulese.xml'],
        dest: '<%= pkg.name %>'
      },
    },
  grunt.loadNpmTasks('grunt-contrib-compress');

  grunt.registerTask('deploy', ['compress:main']);

Thanks for a great starter them with foundation 5!

**Comment by olefredrik** [comment]
Hi @pmccauley . Great suggestion, thanks for your input. I think it might be a nice idea to add this as an option to Gruntfile. But I would perhaps named the task ```grunt package``` or ```grunt bundle``` instead of ```grunt deploy```, as the actual deployment to a server is not a part of what it does.

**Comment by jorcons** [comment]
I suggest use grunt-wordpress-deploy for a real deployment.

**Comment by chriscarpenter12** [comment]
I second @jorcons in adding grunt-wordpress-deploy to be able to easily deploy the site and sync the databases.

**Comment by clearsitedesigns** [comment]
I like adding the grunt-wordpress-deploy. That grunt plugin only sets up a new wordpress instance and has nothing to do with packaging the files as stated above. The task above would package the files into theme.

**Comment by olefredrik** [comment]
There are many different ways to deploy a theme. Some prefer the old-school way with ftp (or preferably sftp). While others prefer deployment through the terminal via ssh. I do not want to go into details on **how** the files should be sent to the Web server.

What we really need is a package command that automates the packaging of only the files needed for deployment. The fix is here: https://github.com/olefredrik/FoundationPress/pull/474

[The feature is described here](https://github.com/olefredrik/FoundationPress#4-compress-all-files-required-for-deployment)
