### ISSUE TITLE
Clearly state what files are needed on server

### ISSUE THREAD

**Issue by llarsson** [olefredrik/FoundationPress#472]
The foundationpress directory contains more than of 10,000 files, due to using `npm` in non-admin mode (`node_modules` directory is huge). The documentation should clearly state which files one actually needs to upload to a server, and which can safely be ignored.

Major bonus points for a hook script that uploads required files to a server, or even just shows a skeleton for how this could be written. :)

**Comment by olefredrik** [comment]
Hi @llarsson , 

Thanks for your feedback. We actually have an [open pull request](https://github.com/olefredrik/FoundationPress/pull/462) on a grunt package command which will bundle all the files that are required on the server and leave the dev dependencies out. I will make sure to clarify how this works in the HOWTO. Unfortunately there is a merge conflict on the pull request, I'm waiting for this to be sorted. 

At the moment we have [some issues with Travis-CI build](https://github.com/travis-ci/travis-ci/issues/4832#issuecomment-141844731), which results in build failures because of a timeout against develop.git.wordpress.org. As soon as this is fixed, I will merge the open pull requests.

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/474

[The feature is described here](https://github.com/olefredrik/FoundationPress#4-compress-all-files-required-for-deployment)
