### ISSUE TITLE
Quickstart used to be better

### ISSUE THREAD

**Issue by Tralapo** [olefredrik/FoundationPress#496]
I've been using FoundationPress for a long time now, but I'm quite confused with the new style this is in now. For example the Quickstart. It's very minimal, while it used to be good.

You now advise us to only install NodeJS, but for Windows user this won't work. You also need Git and you need Ruby if you want to use the same comments as in the Quickstart. Foundation (over at Zurb I mean) does advise to install those. Maybe link to there?

The github clone is also not working, because it will fail over a key. A reference to ```git clone https://github.com/olefredrik/FoundationPress.git``` used to be there in earlier versions for people running into this issue, why is that gone? It's quite useful information I would say.

I do have a question about the new way you're working in, because I can't find it in the docs: How do I perform a ```foundation update```? You don't use the bower_components folder any more I believe? I believe it's /assets/components now, right? Will that go OK when I just do a ```foundation update```?

**Comment by olefredrik** [comment]
Hi @Tralapo ,

For various reasons we have decided to ditch the use of global dependencies in this project. However, if you have Grunt installed globally, you can still use ```grunt build``` and ```grunt watch```. In any case, ```npm run build``` and ```npm run watch``` should work just fine.

You will not need to install anything but Node.js to get started. Just clone (or download) the repository, enter the theme directory and run ```npm install```. If that for some reason should not work, please provide some more info about the errors you get. 

Regarding cloning the repo, this information is still valid:

If you get an error saying Permission denied (publickey) when cloning the repository, use the https protocol instead:  ```git clone https://github.com/olefredrik/FoundationPress.git```

This information was taken away because it is a general information about git, rather than specifically for this project. But you have a point. If more are struggling with this, perhaps we should bring it back to the quickstart.

You can still do a ```foundation update``` to fetch the latest updates from the Zurb Foundation repository. In order to do this, you will (unfortunately) need to have Bower and Ruby installed on your dev environment. If you're using OSX El Capitan, [this guide](https://gorails.com/setup/osx/10.11-el-capitan) might come in handy.

It is in this project nature to be improved and further developed. If you wish to use earlier versions, you're free to grab earlier versions in the [release archive](https://github.com/olefredrik/FoundationPress/releases). There is also a changelog all changes that have been made.

**Comment by Tralapo** [comment]
I would say it's good to include the https version again in the Quickstart, because why not? The other one didn't work for me in Windows 10 at the moment and I remembered it used to be there, but it can puzzle new users. By the way, Windows does not come with git out of the box, so you have to install that to be able to follow your guide. 'Clone' won't work with NodeJS only. But I think people can figure that out by themselves. 

A ```foundation update``` won't create a bower_update folder? Since you changed that basic Foundation part. It will update in assets/components?

Used FoundationPress for several websites, keep doing the good work! With a new project coming up, I was a bit surprised with the new way of ordering the files now. Cheers!

**Comment by FlatspinZA** [comment]
I second the re-inclusion of `git clone https://github.com/olefredrik/FoundationPress.git` in the Quickstart - I also had to remember that there was an issue with this when doing a new installation after the changes.

**Comment by olefredrik** [comment]
Fixed. https://github.com/olefredrik/FoundationPress/pull/509

**Comment by olefredrik** [comment]
A ```foundation update``` won't create a bower_components folder as the ```assets/components``` folder is specified in .bowerrc.
