### ISSUE TITLE
What did you do with the old 5.5.1 version?

### ISSUE THREAD

**Issue by nandroid** [olefredrik/FoundationPress#498]
Hi, I have some websites done with the 5.5.1 version of FoundationPress (no SASS required).
I can't install bower and I always have lots of problems with dependencies and all those things I don't know.
If I update the theme I will lose lots of websites!!

**Comment by olefredrik** [comment]
I don't quite understand why you would choose to use this starter-theme if you don't use Sass? 

That said, you don't need bower and grunt installed as global dependencies to run FoundationPress. If you've installed Node.js, it is enough to download the theme and run an ```npm install``` initially. Then you will have all the files you need. You can then override all styles directly with css in style.css, although this is not recommended.

**Comment by Aetles** [comment]
I would guess that there's actually a lot of users of FoundationPress that is using it without SASS. We've seen it when the compiled CSS was removed from repository. My guess is that a lot of users was just looking for a WordPress theme with Foundation 5 and found this and used it in its original state instead of using it like it was "meant" to be used.

**Comment by olefredrik** [comment]
For those who are looking to hack at the css without using Sass at all, I would recommend taking a look at [JointsWP](http://jointswp.com/). Haven't used it myself, but I know that it's regularly updated and maintained by a group of dedicated and skilled people.
