### ISSUE TITLE
Is FoundationPress based on Reverie 4?

### ISSUE THREAD

**Issue by Aetles** [olefredrik/FoundationPress#499]
So, I question I've been meaning to ask: Is FoundationPress based on Reverie 4? 

When I compare the code from [Reverie 4](https://github.com/milohuang/reverie/tree/747e2c9e796a03fd7574b022ce924e540966ecf0) to the [first commit of FoundationPress](https://github.com/olefredrik/FoundationPress/tree/8f96cc1f0d86fa0eed0e92a8dbfcd323563b5d51) it looks a lot like FoundationPress started as a fork of Reverie 4. A lot of the templates and functions looks the same. For example [cleanup.php](https://github.com/olefredrik/FoundationPress/blob/8f96cc1f0d86fa0eed0e92a8dbfcd323563b5d51/library/cleanup.php) has the same functions and even comments as [clean.php](https://github.com/milohuang/reverie/blob/747e2c9e796a03fd7574b022ce924e540966ecf0/lib/clean.php) and there is even a [function called](https://github.com/olefredrik/FoundationPress/blob/8f96cc1f0d86fa0eed0e92a8dbfcd323563b5d51/archive.php#L19) named `reverie_pagination()` that was later renamed. Yet I have not seen any credit to Reverie anywhere.

**Comment by olefredrik** [comment]
Hi @Aetles ,
Good question. When I first created this repo back in 2013, I did it because I needed an ideal starting point for new web projects.

FoundationPress was initially made up of various functions and classes, borrowed from other and similar themes, as reverie and required +. As time went on, there were several who wanted to contribute and improve this theme. This was totally unexpected, and not my intention from the start.

I could definitely have been better to leave credits for all snippets that have been borrowed from other sources, as the project has evolved. There are a few snippets [here](https://github.com/olefredrik/FoundationPress/blob/master/library/foundation.php#L79) and [there](https://github.com/olefredrik/FoundationPress/blob/master/library/navigation.php#L104) where the source is mentioned, but this is unfortunately not implemented everywhere. 

As of now there are over 50 contributors on the project. The credit is shared among all those who have written code, had code reviews, listed issues etc. And of course those who have written code on other open-source projects that have provided a starting point for this project.

**Comment by Aetles** [comment]
Ok, I was mostly curious since I was a user of Reverie before FoundationPress was created, and I recognized the code. Also I like to go back in the history of code to trace the origin of various code and functions to understand why/when they were added and if I really need them (like the troubled `img_unautop()`). 

The reason I went with FoundationPress was the need for a Grunt/Sass based workflow which Reverie (and many other Foundation-based WordPress themes) lacked at the time. I would guess a lot of others felt the same way. Since Github is such a good environment for collaboration and contributions I guess that just comes automatically when something becomes popular here.

**Comment by olefredrik** [comment]
Ironically, I've probably spent 10 times as much time on maintaining and further developing FP, than actucally use it in projects. My professional career has in recent years taken a shift from public web projects to UI design for business applications. So I'm actually quite happy to have this small side project, which I can learn from. The open-source community has proven to be an amazing place to share experiences and knowledge. Hope you will continue to contribute in responding to issues and pull requests, when you have time :)
