### ISSUE TITLE
Stripping Image Classes

### ISSUE THREAD

**Issue by jsoningram** [olefredrik/FoundationPress#532]
Hi Ole,

Thanks for the great work on FoundationPress. 

In recreate_img_tag() you're only allowing alignment classes on images. Just curious why that is. I had an issue with a site I'm working on where I needed some extra classes applied to images but they were being stripped out.

Thanks again!

**Comment by phylaxis** [comment]
Why was this issue closed? I too have just encountered this issue. What's the fix?

**Comment by jsoningram** [comment]
I copied library/cleanup.php to my child theme and replaced the $allowed_classes array on line 174 with the following ```$allowed_classes = $class_segs;``` so all classes are left as is.

**Comment by olefredrik** [comment]
After the last comment, it looks as if the whole ```library/cleanup.php```needs an update. I'll go through the functions and see which ones are still necessary. I'll also take a fresh look at this specific issue.

**Comment by jhollo** [comment]
I'm still having the image alignment problem as well. WP 4.4.1. Not clear on the fixes above as cleanup has changed, maybe looking in the wrong place?

**Comment by phylaxis** [comment]
Just to add to the list of issues with cleanup.php I was getting XML errors from Facebook avatar images brought in using the [WP Social Login](http://miled.github.io/wordpress-social-login/) plug-in. This issue again was the `Foundationpress_img_rebuilder` class in the `cleanup.php` file. I had to comment out line 145 so that the filter in the `get_avatar` method was not run.

**Comment by olefredrik** [comment]
Fixed https://github.com/olefredrik/FoundationPress/pull/657

**Comment by jhollo** [comment]
Fantastic.
working as expected now. thanks.
