### ISSUE TITLE
Question: Any plans for Genesis integration?

### ISSUE THREAD

**Issue by christopherarter** [olefredrik/FoundationPress#542]
First, thanks for creating this theme. I'm really enjoying Foundation!

Will FoundationPress ever release a Genesis child theme version?

**Comment by olefredrik** [comment]
Hi @christopherarter ,

I have no experience with the Genesis Framework for WordPress. Because I've never used it myself, I have also little experience with pros & cons. So to answer your question, this is not on my TODO-list at the moment. 

However, I've been wanting to separate the UI markup code with the programming logic for a while. Since WordPress does not come with a built-in templating engine, I thought it would be nice to use [Timber](http://upstatement.com/timber/), which seems to be quite good at this.

The first thing that will happen is an update to Foundation 6. In my view, it does not make sense to make big changes before this is in place.
