### ISSUE TITLE
Thoughts on "Eliminate render-blocking JavaScript and CSS in above-the-fold content"?

### ISSUE THREAD

**Issue by dberz** [olefredrik/FoundationPress#543]
Love this project.  It's my go to for all wordpress sites!

Question as you plan for FoundationPress v6...

My FoundationPress sites always get penalized in Google's PageSpeed insights for render-blocking JavaScript and CSS.

For example: https://developers.google.com/speed/pagespeed/insights/?url=parsleyhealth.com

Is there another approach that can be taken as you design the new V6 codebase?

**Comment by olefredrik** [comment]
Hi @dberz ,

Page Speed is, and should always be, a top priority. In FoundationPress there are two javascripts loaded in the header out of the box; fastclick and modernizr. Unfortunately both of these scripts needs to be added in the head section of the document in order to function properly. 

FastClick is a simple library for eliminating the 300ms delay between a physical tap and the firing of a click event on mobile browsers. The aim is to make your application feel less laggy and more responsive while avoiding any interference with your current logic.

Modernizr is used for feature detection such as portrait and landscape. It's also used for the visibility classes. 

On your web site it seems that you have 28 render-blocking script resources and 27 render-blocing style resources. From what I can see, this comes mainly from the use of external plugins

![blocking-scripts-styles](https://cloud.githubusercontent.com/assets/1080017/11014720/f249df84-8543-11e5-933d-96e00ba04ade.png)

Chris Coyier has written [a blog post](https://css-tricks.com/taking-control-cssjs-wordpress-plugins-load/) that sheds light on this issue, with different solutions to fix this.

The main focus of the Foundation 6 release has been to [ditch the bloat and make a lighter framework](http://zurb.com/article/1373/hit-the-weights-and-take-the-bloat-out-of). This will (hopefully) result in improved performance and optimized page speed. 

I have no set date for when FoundationPress will be upgraded to Foundation 6. But it will happen. Earlier versions based on F5 will always be available for download in the release archive.

**Comment by dberz** [comment]
Fantastic response.  Very helpful.  Yes, my sites use a ton of plugins and I'll look to the CSS-Tricks post to get these guys under control!

**Comment by kalilinuxtut** [comment]
Simply put this in your .htaccess file and save it.

```
<filesMatch ".(ico|pdf|flv|jpg|jpeg|png|gif|js|css|swf)$">
Header set Cache-Control "max-age=84600, public"
</filesMatch>

## EXPIRES HEADER CACHING ##
<IfModule mod_expires.c>
ExpiresActive On
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType text/css "access 1 month"
ExpiresByType application/pdf "access 1 month"
ExpiresByType application/javascript "access 1 month"
ExpiresByType application/x-javascript "access 1 month"
ExpiresByType application/x-shockwave-flash "access 1 month"
ExpiresByType image/x-icon "access 1 year"
ExpiresDefault "access 2 days"
</IfModule>
## EXPIRES HEADER CACHING ##
```


Source [http://blogmetric.org/eliminate-render-blocking-javascript-css/](url)
