### ISSUE TITLE
No rss/atom link? 

### ISSUE THREAD

**Issue by justingit** [olefredrik/FoundationPress#566]
Am I correct in seeing that there is no rss/atom link in the head of the templates? 

...reason?

**Comment by Tralapo** [comment]
This is done in cleanup.php: https://github.com/olefredrik/FoundationPress/blob/master/library/cleanup.php

If you remove the line about the RSS-feed it will come back.

**Comment by olefredrik** [comment]
Yes it's by design. WordPress outputs a lot of junk in the ´´<head>´´ by default. Feel free to include this if you need it in your project.

See this file:
https://github.com/olefredrik/FoundationPress/blob/master/library/cleanup.php

To load all the stuff that's included by default (including rss/atom link), remove this line
https://github.com/olefredrik/FoundationPress/blob/master/library/cleanup.php#L36
