### ISSUE TITLE
npm WARN cannot run in wd / bower EACCES: permission denied, mkdir

### ISSUE THREAD

**Issue by bej-soan** [olefredrik/FoundationPress#596]
Hi, 

I again came along the following `cannot run in wd` bug and I guess I found a workaround and thought I might share it here. Maybe it will help others or we can take a look at the source (read about it here already, but solution is not clear to me)

Bower version: 1.7.0
Node version: 4.2.2

The bug appears during `npm install`
```
bjoern:FoundationPress bjoern$ sudo npm install
Password:
npm WARN cannot run in wd foundationpress@2.1.0 bower install && gulp build (wd=/Users/bjoern/MAMP/xxx/wp-content/themes/FoundationPress)
```

When I use just `bower install` I get
```
bower foundation-sites#~6.0.1   cached git://github.com/zurb/foundation-sites.git#6.0.5
bower foundation-sites#~6.0.1 validate 6.0.5 against git://github.com/zurb/foundation-sites.git#~6.0.1
bower motion-ui#~1.1.0          cached git://github.com/zurb/motion-ui.git#1.1.1
bower motion-ui#~1.1.0        validate 1.1.1 against git://github.com/zurb/motion-ui.git#~1.1.0
bower fontawesome#~4.4.0        cached git://github.com/FortAwesome/Font-Awesome.git#4.4.0
bower fontawesome#~4.4.0      validate 4.4.0 against git://github.com/FortAwesome/Font-Awesome.git#~4.4.0
bower jquery#~2.1.4             cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#~2.1.4           validate 2.1.4 against git://github.com/jquery/jquery.git#~2.1.4
bower what-input#~1.1.2         cached git://github.com/ten1seven/what-input.git#1.1.3
bower what-input#~1.1.2       validate 1.1.3 against git://github.com/ten1seven/what-input.git#~1.1.2
bower                           EACCES EACCES: permission denied, mkdir '/Users/xxx/MAMP/xxx/wp-content/themes/FoundationPress/assets/components'

Stack trace:
Error: EACCES: permission denied, mkdir '/Users/xxx/MAMP/xxx/wp-content/themes/FoundationPress/assets/components'
    at Error (native)

Console trace:
Error
    at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:110:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/usr/local/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/local/lib/node_modules/bower/lib/commands/index.js:68:20
    at _rejected (/usr/local/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /usr/local/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/usr/local/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.0
Node version: 4.2.2
OS: Darwin 15.0.0 x64
```

So the theres a permission problem at assets/components, so I used 
`sudo chown -R username /Users/username/MAMP/xxx/wp-content/themes/FoundationPress/assets/` 
on the asset folder. 

After this `bower install` seemed to work, `gulp build` did not work. 
So I used `npm build` and this now works.

Sorry If this is a bit confusing, but npm and stuff is try and error for me.

**Comment by colin-marshall** [comment]
I hear you on the trial and error with npm. 

You should not run `sudo` when you run `npm install`. That would probably take care of your first issue with the permissions. Not sure about the other stuff but it might all be related. The only time you should need to run npm install with sudo is when you are installing a node module globally, and even then it's not a good practice because your permissions  are setup incorrectly.

Try deleting the contents of node_modules and assets/components and run just npm install and see if that works. Beyond that I would uninstall node/npm and reinstall it through Homebrew. I did this a few months back and ever since I have never had to use sudo with npm in any context and life seems to be easier. :+1:

**Comment by josh-rathke** [comment]
Just ran into this actually. Depends on how you have your machine configured when you install everything. This should fix your problem though, essentially the issue has to do with you not having ownership of the .npm directory.

```
sudo chown -R $(whoami) ~/.npm
```

**Comment by colin-marshall** [comment]
You can run `npm config get prefix` to get the path to your npm installation. Then run the command @josh-rathke suggested and replace `~/.npm` with the path you found in your previous step if it's different from `~/.npm`.

@bej-soan you should read this first to be safe:
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by bej-soan** [comment]
@colin-marshall  thank you for the link, I will try this. I ran into erros without `sudo` at `npm install`, can't remeber which one right now but I did not use `sudo` without a reason.

**Comment by Aetles** [comment]
I've done the same thing as colin-marshall, I uninstalled node/npm and reinstalled them with Homebrew so that I did not have to use `sudo` any more. I read some articles that helped me, like [this](http://www.johnpapa.net/how-to-use-npm-global-without-sudo-on-osx/), [this](http://blog.teamtreehouse.com/install-node-js-npm-mac) and [this](https://gist.github.com/TonyMtz/d75101d9bdf764c890ef).

**Comment by LukePettway** [comment]
@Aetles thanks for sharing the links, I haven't really used Homebrew but now I want to check it out.
