### ISSUE TITLE
validator errors

### ISSUE THREAD

**Issue by jimlongo56** [olefredrik/FoundationPress#614]
Hi, line 16 in **single.php** produces a duplicate class attribute.

   ` <article class="main-content" <?php post_class() ?> id="post-<?php the_ID(); ?>">`
results in something like this . . . 
   ` <article class="main-content" class="post-1 post type-post status-publish format-standard hentry category-uncategorized" id="post-1">`

Additionally there are three stray closing divs in **footer.php** that aren't  required.
lines 25, 26, 30

**Comment by olefredrik** [comment]
Hi, 

Thanks! The duplicate class attribute error has now been fixed https://github.com/olefredrik/FoundationPress/pull/616

The closing divs in **footer.php** should only be applied when off-canvas is selected as the mobile menu option in customizer. Fixed in https://github.com/olefredrik/FoundationPress/pull/615
