### ISSUE TITLE
sorry for the dumb question, but how do you update

### ISSUE THREAD

**Issue by nitrokevin** [olefredrik/FoundationPress#689]
Once you have started building a site, what is the correct way to update foundation press?

Also should I be making a _customsettings.scss file and importing that rather than making changes to the _settings.scss file 

Sorry complete noob questions, I just want to get it right

**Comment by colin-marshall** [comment]
Updating is a tricky subject since this is a starter theme. There is a good discussion of the best options on this issue: https://github.com/olefredrik/FoundationPress/issues/663.

Make changes to the settings file located at `/assets/scss/global/_settings.scss`. You can use a custom settings file instead if you prefer. That would make updating the settings file easier when new variables are added with updates to Foundation 6.
