### ISSUE TITLE
cant click parent links in Off-Canvas Navigation

### ISSUE THREAD

**Issue by LepusSorbas** [olefredrik/FoundationPress#710]
Hello, when i'm clicking links in the Off Canvas Navigation, just the submenu is opening/closing instead of linking me to the page. Anyone have the same problem? regards Manuel

**Comment by adibbz** [comment]
+1 Trying to figure out best solution. In previous versions of FoundationPress I could remove the navigation walker and display all the submenu links below. 

Would love to find a better solution.

**Comment by JeremyEnglert** [comment]
If you're using the drilldown menu, you'll need to set `data-parent-link` to `true`.

http://foundation.zurb.com/sites/docs/drilldown-menu.html#js-options

**Comment by adibbz** [comment]
Has anyone found a good solution when using off-canvas menu?

**Comment by olefredrik** [comment]
This is not really a technical issue. As we're using an accordion menu for the off-canvas sub-menu, the parent item can not be clicked, because it is set up to be the trigger for expanding and collapsing the menu. A workaround would be to add the content for the parent page in the expanded sub-menu, like this

```
- Countries (parent item. will only expand and collapse the list)
-- View all countries (contains the content for the parent item. can be clicked)
-- Norway
-- Sweden
-- Denmark
-- Finland
```

Alternatively we could redesign the off-canvas and make the expand/collapse button a separate link, and not part of the parent menu link. But that would require some work. If anyone wants to have a look at it, pull requests are always welcome.

**Comment by olefredrik** [comment]
Hold on. There is a setting on the Accordion Menu in Foundation that takes care of this: http://foundation.zurb.com/sites/docs/accordion-menu.html#submenu-toggle

I will push an update that fixes this issue soon.

**Comment by melcarthus** [comment]
Why is there not the same thing for the drilldown menu? This is the only thing t hat comes close to make the parent element link clickable.
