### ISSUE TITLE
Changing the topbar breakpoint

### ISSUE THREAD

**Issue by GarySwift** [olefredrik/FoundationPress#729]
This should be an easy fix but I can't seem to figure it after lots of trying.

Where do I change the breakpoint for switching between desktop topbar and mobile. On a clean installation of FoundationPress, the desktop topbar shows on iPad size screen. I want to always show the mobile menu on any device smaller than desktop resolution.

**Comment by olefredrik** [comment]
Hi @GarySwift ,

Please see this related issue https://github.com/olefredrik/FoundationPress/issues/726

**Comment by GarySwift** [comment]
Hi @olefredrik 

Exactly what I was looking for. Thank You. I was expecting to make change in the scss like previous versions of Foundation.

**For anyone one else that has a similar issue, here is the how to do it:**

Unlike previous versions of Foundation, we need to alter the mark up in `header.php`.

Add the attribute **data-hide-for="large"** to the element (second line) with class `.title-bar` and attribute `data-responsive-toggle="site-navigation" `.

```
	<header id="masthead" class="site-header" role="banner">
		<div class="title-bar" data-responsive-toggle="site-navigation" data-hide-for="large">
			<button class="menu-icon" type="button" data-toggle="mobile-menu"></button>
			<div class="title-bar-title">
				<a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a>
			</div>
		</div>

		<nav id="site-navigation" class="main-navigation top-bar" role="navigation">
			...
		</nav>
	</header>
```

**Comment by olefredrik** [comment]
:+1:

**Comment by Larzans** [comment]
I am not sure if it had to do sth. with my setup, but i ALSO had to change the **scss/modules/_navigation.scss** file and change the visibility for the menus. In order to do that i created a custom breakpoint in **scss/global/_settings.scss**.
This is the whole process:
1. create a new breakpoint 'navbar' in scss/global/_settings.scss (~line 80)
`$breakpoints: (small: 0, medium: 640px, navbar: 840px, large: 1024px, xlarge: 1200px, xxlarge: 1440px,);`
`$breakpoint-classes: (small medium large navbar);`
2. change the menu visibility by using the new breakpoint in scss/modules/_navigation.scss ( first lines )
`.desktop-menu, .top-bar-left { @include show-for(navbar); }`
`#mobile-menu, .title-bar { @include hide-for(navbar); }`
3. use the new breakpoint in header.php
`<div class="title-bar" data-responsive-toggle="site-navigation" data-hide-for="navbar">`
