### ISSUE TITLE
WP Search, show excerpts in search

### ISSUE THREAD

**Issue by jkaliski** [olefredrik/FoundationPress#732]
What is the proper way of displaying posts excerpts in the search results instead of full posts in FundationPress?

**Comment by rafaoski** [comment]
I m sory  but my english is weak ... You must go to root folder foundationpress and search results is located in template-parts folder in file name content.php (this file show results in blog post)... 
Change line number 19   <?php  the_content( __( 'Continue reading...', 'foundationpress' ) ); ?>  to <?php the_excerpt(); ?> ... But blog post also change ... If you want change only searc to add this block in     template-parts/content.php (Delete Line 19) ...
ADD:
          <?php if(is_search()) : //If Search ?>
            
            <?php the_excerpt(); //Add Excerpt ?>
            
            <?php else : //Else Not Search  ?>
            
		<?php the_content( __( 'Continue reading...', 'foundationpress' ) ); //Add Content ?>
            
         <?php endif; //End :) ?>

**Comment by jkaliski** [comment]
It worked with  <?php the_excerpt(); ?> , in the content.php, thanks a lot! I did not quite understand what you meant by blog post also changes...

**Comment by rafaoski** [comment]
If You look at the page with the all entries you'll see excerpt (because added <?php the_excerpt(); ?> ... 
Earlier, before the Change was the Display all words ...
This is correct way ...
Added entries automatically shortened ...
Look on this Page: https://developer.wordpress.org/reference/functions/the_excerpt/
Good luck my friend ...

**Comment by jkaliski** [comment]
thank you !
