### ISSUE TITLE
Incorrect GCC

### ISSUE THREAD

**Issue by d4vidmiller** [olefredrik/FoundationPress#739]
Hello

So with the recent update and libsass, it seems CENTOS 6.7 contains an outdated version of GCC. As there is yet another issue to worry about, my thoughts are how could we change up the way we deploy. Your npm run package seems to be a good way to build and package up a file, so what is the best way to deploy to a production site this way, and if its the best way.

D.

**Comment by olefredrik** [comment]
Hi, 

Unfortunately I do not know what the GCC is. FoundationPress has no guidelines for deployment routines at all. You can run ```npm run production``` to minify your css and js, or run ```npm run package``` to create a minified and production ready .zip containing your theme. Since deployment can happen in a hundred different ways, this is out of scope for FP.

**Comment by d4vidmiller** [comment]
Alright, but I do suggest making note that as libsass requires a version of GCC not native with CENTOS 6.7, there will be issues compiling.

**Comment by olefredrik** [comment]
Allright. Thanks for sharing!
