### ISSUE TITLE
localhost:3000 issue

### ISSUE THREAD

**Issue by fatbuddha-design** [olefredrik/FoundationPress#749]
Hello
I have just installed the latest version of FoundationPress via, git,npm install and npm run watch.

I have changed the gulp file as below :-

// Enter URL of your local server here
// Example: 'http://localwebsite.dev'
var URL = 'http://localhost:8080';

All goes well until browser-sync kicks in, I then get the file served to localhost:3000.

I am very new to the localhost part as I have been using Prepros with Foundation 5, and then Foundation 6 with Browser-sync but both of those worked out of the box.

I have Windows10 with IIS10, if I type localhost:8080 into my browser this serves to the IIS welcome page.
I also have Winamp (not sure if this is required for FoundationPress) and I have changed the httpd.conf to Listen 12.34.56.78:8080 Listen 0.0.0.0:8080Listen[::0]:8080

Below is a portion of the cmd prompt log -

C:\Users\Will\Documents\Web Design\WordPress\FoundationPress\One>npm run watch

> foundationpress@2.5.0 watch C:\Users\Will\Documents\Web Design\WordPress\FoundationPress\One
> gulp

[18:10:47] Using gulpfile ~\Documents\Web Design\WordPress\FoundationPress\One\gulpfile.js
[18:10:47] Starting 'clean'...
[18:10:47] Starting 'clean:javascript'...
[18:10:47] Starting 'clean:css'...
[18:10:47] Finished 'clean:javascript' after 70 ms
[18:10:47] Finished 'clean:css' after 54 ms
[18:10:47] Finished 'clean' after 96 ms
[18:10:47] Starting 'build'...
[18:10:47] Starting 'copy'...
[18:10:47] Finished 'copy' after 660 ms
[18:10:47] Starting 'sass'...
[18:10:52] Starting 'javascript'...
[18:10:58] Starting 'lint'...
[18:11:21] Finished 'lint' after 23 s
[18:11:21] Finished 'sass' after 34 s
[18:11:27] Finished 'javascript' after 35 s
[18:11:27] Finished 'build' after 41 s
[18:11:27] Starting 'browser-sync'...
[18:11:27] Finished 'browser-sync' after 103 ms
[18:11:27] Starting 'default'...
[18:11:28] Finished 'default' after 145 ms
[BS] Proxying: http://localhost:8080
[BS] Access URLs:

Local: http://localhost:3000
External: http://192.168.1.87:3000

 UI: http://localhost:3001
 UI External: http://192.168.1.87:3001

[BS] Watching files...

I am assuming that when set up correctly, the page will load into browser-sync and any changes made to html code or scss files will be reflected.
Has anyone succeeded in getting this type of set-up to work? if so what changes do i need to make?

Many Thanks

Will

**Comment by olefredrik** [comment]
Hi Will, 

Are you running WordPress on your IIS server? Didn't know that was possible. I know you can use local WAMP server in Windows to host your local WordPress install. In WAMP you can specify an alias-name or dynamic dns. This would be your localhost URL to put in gulpfile.js. Check out [this guide](https://premium.wpmudev.org/blog/how-to-set-up-wordpress-locally-for-pcwindows-with-wamp/) for setting up WAMP on Windows.

Please let me know if this works for you.

**Comment by FlatspinZA** [comment]
I've been using WebMatrix to serve my files, instead of WAMP. It's actually quite simple, because you can use the UI to change the PHP version before you launch your site (for instance, Drupal 8 won't go anywhere unless you're using PHP 5.5.3), but besides that - everything just works if you follow the instructions.

I still get browsersync serving me on localhost:3000, and my CSS changes are reflected immediately. 

Installation is really simple, too. Install Webmatrix, copy the base installation files for WP into your working directory, launch Webmatrix, open from folder, and straight away you are notified PHP needs to be installed as a dependency. After that, run site, install Wordpress, install FoundationPress, and Bob's your Uncle. 

Well, actually, you still need MySQL, but that problem can be solved by installing any Wordpress/Joomla/Drupal site from the WebMatrix App Gallery - I just delete them afterwards, because all I want is the MySQL server installed. Updating to a newer version is another issue. 

For me, it's a lot simpler than all the WAMP configuration issues.

**Comment by jmbarlow** [comment]
For a local dev environment, you might like [Varying Vagrant Vagrants](https://github.com/Varying-Vagrant-Vagrants/VVV). It's a turn-key wordpress dev box.

**Comment by colin-marshall** [comment]
@fatbuddha-design I'm going to close this for now since we have no response from you. Feel free to reopen it with the requested information if you still need help.
