### ISSUE TITLE
Should Aside be used for the sidebar?

### ISSUE THREAD

**Issue by LukePettway** [olefredrik/FoundationPress#798]
I was reading an article yesterday about the HTML5 document outline and noticed that the person wasn't using Aside for a sidebar, which I thought was odd, then I did some digging into it and learned that there are good reasons to not do so:

http://codepen.io/mi-lee/post/an-overview-of-html5-semantics

"The most common misconception of how this element should be used is for the standard sidebar. While there is usually a degree of relation between sidebar content and the content in an article, it is not enough to be considered fit for an <aside>. Navigation, ads, search boxes, blogrolls and so on are not directly related to the article and therefore do not justify the use of an <aside>."

http://codepen.io/mi-lee/post/an-overview-of-html5-semantics

"a sidebar - it should not belong to the main outline of the HTML doc and aren’t usually rendered by assistive technologies"

Based on those two posts, I wonder if using <aside> in the context of a sidebar is correct. It doesn't seem like it is a major problem, just a minor concern at the very least.

**Comment by colin-marshall** [comment]
@LukePettway you make great points here. Would you suggest `<section>` in place of `<aside>`?

**Comment by LukePettway** [comment]
```html <section> ``` might work, or even just a ```html <div id="sidebar"> ``` would be fine. Oddly enough Twenty Sixteen uses an aside, so I guess it isn't such a big deal but just because they are doing it that way doesn't mean it is correct.

**Comment by colin-marshall** [comment]
@olefredrik @Aetles @josh-rathke any input on this?

**Comment by Aetles** [comment]
Not really. Based on the Codepen article and comments it seems like `<aside>` is meant for those little boxes of additional information that is related to an article, rather than the entire sidebar. So based on that it seems like we should change it. But as LukePettway notes, WP is using it in Twenty Sixteen, so maybe it's not that wrong? 

I usually look at Underscores whenever I need guidance an they are using `<aside>` as well in their [sidebar.php](https://github.com/Automattic/_s/blob/master/sidebar.php). It seems like there was [a discussion](https://github.com/Automattic/_s/pull/867) about using `<aside>` for the entire sidebar instead of each widget area. That lead me to [the discussion](https://github.com/WordPress/twentysixteen/issues/355) about the same thing in Twenty Sixteen and it seems like the consensus (even though there was an objection) was that `<aside>` was going to be used for the entire sidebar.

**Comment by olefredrik** [comment]
I really don't have a strong opinion about this, either way. Both ``<aside>`` , ``<section>`` and ``<div>`` will work I guess.
