### ISSUE TITLE
Extra Question For Issues 

### ISSUE THREAD

**Issue by LukePettway** [olefredrik/FoundationPress#811]
I was wondering if it would make sense to add an extra questions, asking for the current version of Node/NPM since it seems like a lot of compiling issues get reported and most of the time it seems to stem from outdated tools. 

Example:

What is your current version of Node and NPM?
(node -v) and (npm -v)

**Comment by colin-marshall** [comment]
I think that's a great idea. I would say that asking for npm version is unnecessary though since there is only one version used with each version of Node.

I recommend these additions to the requested info:
- OS & version
- Node version (`node -v`)
- Foundation version (`bower list`)

It should also state that Node v4+ is required for the current version FoundationPress, which will resolve some issues before they get opened.

**Comment by LukePettway** [comment]
@colin-marshall Good point, those would also be very useful.

**Comment by LukePettway** [comment]
**Please List the Following:**

- OS & version:
- Node version (node -v) [Node v4+ is required] :
- Foundation version (bower list) : 


Does this format work? If so I can submit a PR with changes to the issue template.

**Comment by colin-marshall** [comment]
Looks good! I would just make this change: [Node v4+ is required for FoundationPress v2+]

And then make sure the test case info (below) is still there. The links I used here should get updated with updates to Foundation so make sure you replace the old ones. Thanks @LukePettway!

**Include Test Case** (if applicable):
Give us a link to a CodePen or JSFiddle that recreates the issue.
- [CodePen with Foundation 6 and MotionUI](http://codepen.io/rafibomb/pen/xVVGOB)
- [CodePen with Foundation 6, Flexbox grid and MotionUI](http://codepen.io/rafibomb/pen/jqqPra)

**Comment by olefredrik** [comment]
Thanks, guys! Merged https://github.com/olefredrik/FoundationPress/pull/821
