### ISSUE TITLE
Building a source project using the packaged archive.

### ISSUE THREAD

**Issue by arielnoname** [olefredrik/FoundationPress#881]
I don't know where else to put this. So here it is.

Let's say I lost the foundationpress directory with all the sources of the sass version of foundation, the gulpfile, etc.

I have a backup of a package made with `npm run package`.

Is there any way (or best way from anyone that knows) for me to rebuild the source project so I can use the npm tasks goodies?

I don't know if I'm making myself clear.

Cheers

**Comment by olefredrik** [comment]
The `npm run package` command is meant to be a tool for creating a zip containing the minified, production ready version of your theme. It's not meant to be a complete backup tool for your project. 

I would highly recommend and encourage developers to use git for version control. Simply push your local git repository to a remote repo on Github, Bitbucket or similar so that you have a backup of your project at all times.
