### ISSUE TITLE
Main menu with dropdowns - tapping sub-item link in iOS closes menu, does nothing else

### ISSUE THREAD

**Issue by adambundy** [olefredrik/FoundationPress#975]
FoundationPress 2.9.0

Using Safari on iPad (iOS 9.3.5), in landscape I am above my mobile menu breakpoint, and when tapping a top-level item with sub-items, the submenu reveals as expected, but tapping a sub-item briefly highlights the item, then the menu closes and nothing else happens. These are links to other pages, so transfer to other URL should occur. Not sure if this is a Foundation or FoundationPress issue. Thanks for any assistance.

https://harveststrategygroup.com/

**Comment by dantahoua** [comment]
It's a Foundation bug, it has been corrected in last version. You could install last version of Foundation Press ans just copy the foundation.dropdownMenu.js file.. It worked for me.

**Comment by adambundy** [comment]
Excellent! Thanks for the tip @dantahoua! That worked. Inidentally, does anyone have any resources for how to update a FP install via command line?

**Comment by olefredrik** [comment]
@adambundy : Glad it works now. Updating a FP install via the command line will be a hassle, as it's meant to be a starter-theme that you will hack on and make your own, rather than serving as a parent/child-theme. 

I believe that most people would want to clone the current version of FP when they start a new project. There will probably be so many changes anyway, that you will end up merge conflict hell if you try to pull down the latest version when your project is well under way. :)
